### ISSUE TITLE
do poprawy

### ISSUE THREAD

**Issue by zdolny** [bobrowskibiz/kod8.9#1]
- [x] choinka zaczyna sie od spacji, odejmij 1 w odpowiednich petlach 
- [x] zadeklaruj zmienne w petlach, zeby uniknac ich przenikania do zakresu globalnego (`for (var i = 1 ;...`)
- [x] dodaj wciecia wewnatrz wewnatrznych petli `for`

**Comment by bobrowskibiz** [comment]
Absolutnie nie mam pojęcia gdzie chciałbyś odjąć jedynkę aby całość zaczęła się od * a nie od spacji.

**Comment by zdolny** [comment]
obgadane, wiec zamykam
